name: Build App

on: 
  push: 
    branches: 
      - main

jobs: 
  build-app:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use node 16
        uses: actions/setup-node@v2
        with: 
          node-version: '16.x'

      - name: Install dependencies
        run: npm install

      - name: build app
        run: npm run build
        working-directory: build
      
      - name: Update Build Folder
        run: |
          git config user.email "${{ env.GIT_USER_EMAIL }}"
          git config user.name "${{ env.GIT_USER_NAME }}"
          git add -A
          git commit -m "Update build folder"
          git push origin main
